name: Build CLI tool

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    
    - name: setup go environment
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.5'

    - name: build
      run: go build ./...

    - name: run linter
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
